/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Aes;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Cuentas;

/**
 *
 * @author drap
 */
public class CuentaItem extends javax.swing.JPanel {

    MainFrame mainFrame;
    Cuentas cuenta;
    Aes aes;

    /**
     * Creates new form CuentaItem
     */
    public CuentaItem(MainFrame mainFrame, Cuentas cuenta) {
        initComponents();
        this.mainFrame = mainFrame;
        this.cuenta = cuenta;
        this.descripcion.setText(cuenta.getDescripcion());
        this.usuario.setText(cuenta.getNombre());
        aes = new Aes();
        try {
            String pass = aes.decrypt(cuenta.getPass());
            this.pass.setText(pass);
        } catch (Exception ex) {
            Logger.getLogger(CuentaItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        descripcion = new javax.swing.JLabel();

        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setText("Nombre");

        pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass.setText("pass");

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descripcion.setText("Cuenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario)
                    .addComponent(pass)
                    .addComponent(jButton1)
                    .addComponent(descripcion))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainFrame.controller.eliminaCuenta(cuenta);
        mainFrame.goToCuentas();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
