/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Inicio;
import controlador.ManejaUsuario;
import java.awt.BorderLayout;
import java.awt.Label;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Usuarios;

/**
 *
 * @author drap
 */
public class MainFrame extends javax.swing.JFrame {

    public ManejaUsuario controller;
    LoginPanel loginPanel;
    RegistroPanel registroPanel;
    AppPanel appPanel;
    ModificarPasswordDialog modificarPasswordDialog;
    AñadirCuenta añadirCuenta;
    Usuarios usuario;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        loginPanel = new LoginPanel(this);
        appPanel = new AppPanel(this);
        registroPanel = new RegistroPanel(this);
        modificarPasswordDialog=new ModificarPasswordDialog(this,true);
        modificarPasswordDialog.setVisible(false);
        añadirCuenta = new AñadirCuenta(this, true);
        añadirCuenta.setVisible(false);
        this.setLayout(new BorderLayout());
        this.add(loginPanel);
        //this.add(appPanel);
        //appPanel.setVisible(false);
        controller = new ManejaUsuario();
        //loginPanel.setLocation(0, 0);
        //loginPanel.setVisible(true);
    }
    
    public void goToModificarUsuario(){
        modificarPasswordDialog.setVisible(true);
    }
    
    public void goToAñadirCuenta(){
        añadirCuenta.setVisible(true);
    }
    
    public void login(String usuario, String pass){
        if(controller.login(usuario, pass)){
            this.usuario=controller.obtenUsuario(usuario);
            modificarPasswordDialog.setUsuario(this.usuario);
            añadirCuenta.setUsuario(this.usuario);
            /*this.remove(loginPanel);
            this.add(appPanel);
            this.repaint();
            this.revalidate();
            List<Object[]> cuentas = controller.obtenCuentas(this.usuario);
            System.out.println(cuentas.size());
            appPanel.mostrarCuentas(cuentas);
            repaint();
            revalidate();*/
            goToCuentas();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Las credenciales no coinciden con ningún usuario.",
                    "Login error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void goToCuentas(){
        this.remove(loginPanel);
        this.add(appPanel);
        this.repaint();
        this.revalidate();
        List<Object[]> cuentas = controller.obtenCuentas(usuario);
        appPanel.mostrarCuentas(cuentas);
        repaint();
        revalidate();
    }
    
    public void goToRegistrar(){
        this.remove(loginPanel);
        this.add(registroPanel);
        this.repaint();
        this.revalidate();
    }
    
    public void registrar(String usuario, String pass){
        Usuarios usuarios = new Usuarios(usuario, pass);
        controller.guardaUsuario(usuarios);
        this.remove(registroPanel);
        this.add(loginPanel);
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
