package modelo;
// Generated 22-may-2017 20:29:03 by Hibernate Tools 4.3.1



/**
 * Cuentas generated by hbm2java
 */
public class Cuentas  implements java.io.Serializable {


     private Integer id;
     private Usuarios usuarios;
     private String nombre;
     private String pass;
     private String descripcion;

    public Cuentas() {
    }

    public Cuentas(Usuarios usuarios, String nombre, String pass, String descripcion) {
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.pass = pass;
       this.descripcion = descripcion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


